import 'package:flutter/material.dart';

ThemeData lightTheme=
ThemeData(colorScheme: lightColorScheme,useMaterial3: true,);
const lightColorScheme = ColorScheme(
  brightness: Brightness.light,
  primary: Color(0xFF2A4A54),
  onPrimary: Color(0xFFFFFFFF),
  primaryContainer: Color(0xFF73F8E8),
  onPrimaryContainer: Color(0xFF00201D),
  secondary: Color(0xFF4A635F),
  onSecondary: Color(0xFFFFFFFF),
  secondaryContainer: Color(0xFFCCE8E3),
  onSecondaryContainer: Color(0xFF05201C),
  tertiary: Color(0xFF46617A),
  onTertiary: Color(0xFFFFFFFF),
  tertiaryContainer: Color(0xFFCDE5FF),
  onTertiaryContainer: Color(0xFF001D32),
  error: Color(0xFFBA1A1A),
  errorContainer: Color(0xFFFFDAD6),
  onError: Color(0xFFFFFFFF),
  onErrorContainer: Color(0xFF410002),
  background: Color(0xFFFAFDFB),
  onBackground: Color(0xFF191C1C),
  surface: Color(0xFFFAFDFB),
  onSurface: Color(0xFF191C1C),
  surfaceVariant: Color(0xFFDAE5E2),
  onSurfaceVariant: Color(0xFF3F4947),
  outline: Color(0xFF6F7977),
  onInverseSurface: Color(0xFFEFF1EF),
  inverseSurface: Color(0xFF2D3130),
  inversePrimary: Color(0xFF52DBCB),
  shadow: Color(0xFF000000),
  surfaceTint: Color(0xFF006A61),
  outlineVariant: Color(0xFFBEC9C6),
  scrim: Color(0xFF000000),
);
ThemeData darkTheme=ThemeData(colorScheme: darkColorScheme,useMaterial3: true);
const darkColorScheme = ColorScheme(
  brightness: Brightness.dark,
  primary: Color(0xFF01DEB0),
  onPrimary: Color(0xFFFFFFFF),
  primaryContainer: Color(0xFF2CD3C9),
  onPrimaryContainer: Color(0xFF73F8E8),
  secondary: Color(0xFFFFFFFF),
  onSecondary: Color(0xFF1C3531),
  secondaryContainer: Color(0xFFF4FFFF),
  onSecondaryContainer: Color(0xFFCCE8E3),
  tertiary: Color(0xFFFFFFFF),
  onTertiary: Color(0xFFE8DEDE),
  tertiaryContainer: Color(0xFFD6E2EF),
  onTertiaryContainer: Color(0xFFFFFFFF),
  error: Color(0xFFFFB4AB),
  errorContainer: Color(0xFF93000A),
  onError: Color(0xFF690005),
  onErrorContainer: Color(0xFFFFDAD6),
  background: Color(0xFF191C1C),
  onBackground: Color(0xFFE0E3E1),
  surface: Color(0xFF191C1C),
  onSurface: Color(0xFFE0E3E1),
  surfaceVariant: Color(0xFFD2E0DD),
  onSurfaceVariant: Color(0xFFFFFFFF),
  outline: Color(0xFFFFFFFF),
  onInverseSurface: Color(0xFFF4FFFF),
  inverseSurface: Color(0xFFE0E3E1),
  inversePrimary: Color(0xFF006A61),
  shadow: Color(0xFF000000),
  surfaceTint: Color(0xFF52DBCB),
  outlineVariant: Color(0xFFFFFFFF),
  scrim: Color(0xFF000000),
);