// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlIiWIzkDq1sFo1CT7BYU5fnBahVduads',
    appId: '1:752361253755:web:465840b19e09f6b5c9abde',
    messagingSenderId: '752361253755',
    projectId: 'todo-app-f5977',
    authDomain: 'todo-app-f5977.firebaseapp.com',
    storageBucket: 'todo-app-f5977.appspot.com',
    measurementId: 'G-JLJXS8J0DW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUXpfAfJ9V1dr0TN5lUDNKWEWx_EC8W5g',
    appId: '1:752361253755:android:e09736eb1e095c3cc9abde',
    messagingSenderId: '752361253755',
    projectId: 'todo-app-f5977',
    storageBucket: 'todo-app-f5977.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN6IN_2jgntO9p3Jf6ZxErhlIjXlYsuRw',
    appId: '1:752361253755:ios:e33128744cea327bc9abde',
    messagingSenderId: '752361253755',
    projectId: 'todo-app-f5977',
    storageBucket: 'todo-app-f5977.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBN6IN_2jgntO9p3Jf6ZxErhlIjXlYsuRw',
    appId: '1:752361253755:ios:e33128744cea327bc9abde',
    messagingSenderId: '752361253755',
    projectId: 'todo-app-f5977',
    storageBucket: 'todo-app-f5977.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlIiWIzkDq1sFo1CT7BYU5fnBahVduads',
    appId: '1:752361253755:web:987620b8793a42dec9abde',
    messagingSenderId: '752361253755',
    projectId: 'todo-app-f5977',
    authDomain: 'todo-app-f5977.firebaseapp.com',
    storageBucket: 'todo-app-f5977.appspot.com',
    measurementId: 'G-MNTJH9PYBZ',
  );
}
